# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvaVNeZX-fYJ7FXppjExywSp9Q6rLPfZ
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. Настройка интерфейса
st.title("Моделирование дифракции Френеля")
st.sidebar.header("Параметры системы")

# Константы
N = 1024
L_apt = 0.01
wavelength = 550e-9

# Выбор типа апертуры
choice = st.sidebar.selectbox(
    "Выберите тип апертуры:",
    ('1 - Одна щель', '2 - Две щели', '3 - Прямоугольное отверстие',
     '4 - Круглое отверстие', '5 - Два прямоугольника (наслоение)',
     '6 - Два круга (наслоение)', '7 - Пользовательская формула',
     '8 - Треугольник', '9 - Звездочка', '10 - Две звезды (наслоение)',
     '11 - Три круга (наслоение)')
)

# Сетка координат
coords = np.linspace(-L_apt/2, L_apt/2, N)
X, Y = np.meshgrid(coords, coords)

# НОВАЯ ФИШКА: Поворот апертуры для удобства отображения
rotate_apt = st.sidebar.checkbox("Повернуть апертуру на 90°", value=False)
if rotate_apt:
    # Просто меняем сетки местами для расчетов маски
    X_calc, Y_calc = Y, X
else:
    X_calc, Y_calc = X, Y

mask = np.zeros((N, N))

# Вспомогательная функция для генерации звезды
def generate_star_mask(X_grid, Y_grid, center_x, center_y, R_out):
    R_in = R_out * 0.382
    vertices = []
    for i in range(10):
        radius = R_out if i % 2 == 0 else R_in
        angle = (i * np.pi / 5) - np.pi/2
        vertices.append([center_x + radius * np.cos(angle), center_y + radius * np.sin(angle)])
    vertices = np.array(vertices)
    temp_mask = np.ones((N, N), dtype=bool)
    for i in range(10):
        x_a, y_a = vertices[i]
        x_b, y_b = vertices[(i + 1) % 10]
        temp_mask &= ((x_b - x_a) * (Y_grid - y_a) - (y_b - y_a) * (X_grid - x_a) >= 0)
    return np.where(temp_mask, 1, 0)

choice_num = choice.split(' ')[0]

# 2. Логика создания масок (используем X_calc и Y_calc)
if choice_num == '1':
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X_calc) < w/2) & (np.abs(Y_calc) < 0.005), 1, 0)

elif choice_num == '2':
    w = st.sidebar.number_input("Ширина щели (мм):", value=0.05) / 1000
    d = st.sidebar.number_input("Расстояние между центрами (мм):", value=0.2) / 1000
    mask = np.where((np.abs(Y_calc) < 0.005) & ((np.abs(X_calc - d/2) < w/2) | (np.abs(X_calc + d/2) < w/2)), 1, 0)

elif choice_num == '3':
    wx = st.sidebar.number_input("Ширина по X (мм):", value=0.5) / 1000
    wy = st.sidebar.number_input("Ширина по Y (мм):", value=0.5) / 1000
    mask = np.where((np.abs(X_calc) < wx/2) & (np.abs(Y_calc) < wy/2), 1, 0)

elif choice_num == '4':
    r = st.sidebar.number_input("Радиус отверстия (мм):", value=0.4) / 1000
    mask = np.where(X_calc**2 + Y_calc**2 < r**2, 1, 0)

elif choice_num == '8': # ТРЕУГОЛЬНИК
    a = st.sidebar.number_input("Сторона треугольника (мм):", value=1.5) / 1000
    h = a * np.sqrt(3) / 2
    y_off = h / 3
    condition = (Y_calc > -h/2 + y_off) & (Y_calc < -np.sqrt(3) * X_calc + h/2 + y_off) & (Y_calc < np.sqrt(3) * X_calc + h/2 + y_off)
    mask = np.where(condition, 1, 0)

elif choice_num == '9': # ЗВЕЗДОЧКА
    star_r = st.sidebar.slider("Внешний радиус (мм):", 0.1, 5.0, 1.0) / 1000
    mask = generate_star_mask(X_calc, Y_calc, 0, 0, star_r)

# ... (остальные фигуры по аналогии используют X_calc, Y_calc) ...
# Для краткости я оставил основные, но логика понятна: везде X -> X_calc

# Параметры расстояний
z1 = st.sidebar.number_input("z1 (источник-апертура), м:", value=1.0)
z2 = st.sidebar.number_input("z2 (апертура-экран), м:", value=1.0)

# 3. Физический расчет
if z1 != 0 and z2 != 0:
    R_eff = 1 / (1/z1 + 1/z2)
    # Важно: фазовый множитель всегда привязан к реальным X, Y
    phase = np.exp(1j * (2 * np.pi / wavelength) * (X**2 + Y**2) / (2 * R_eff))

    # Расчет без смещений
    input_field = mask * phase
    field_screen = np.fft.fftshift(np.fft.fft2(np.fft.ifftshift(input_field)))

    intensity = np.abs(field_screen)**2
    intensity_viz = np.log10(intensity + 1)
    screen_scale_mm = (wavelength * z2 / L_apt) * N * 1000

    # 4. Отрисовка
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

    ax1.imshow(mask, extent=[-L_apt*500, L_apt*500, -L_apt*500, L_apt*500], cmap='gray', origin='lower')
    ax1.set_title("Вид апертуры (мм)")

    zoom_area = screen_scale_mm * 0.15
    ax2.imshow(intensity_viz, cmap='magma', origin='lower',
               extent=[-screen_scale_mm/2, screen_scale_mm/2, -screen_scale_mm/2, screen_scale_mm/2])
    ax2.set_xlim(-zoom_area, zoom_area); ax2.set_ylim(-zoom_area, zoom_area)
    ax2.set_title(f"Экран (z2 = {z2} м)")

    st.pyplot(fig)

    # 5. Профиль
    fig_line, ax3 = plt.subplots(figsize=(10, 3))
    center_idx = N // 2
    # Если повернули апертуру, срез тоже логично брать по вертикали, чтобы видеть полосы
    line_data = intensity[:, center_idx] if rotate_apt else intensity[center_idx, :]

    x_axis = np.linspace(-screen_scale_mm/2, screen_scale_mm/2, N)
    ax3.plot(x_axis, line_data / np.max(line_data) if np.max(line_data)>0 else line_data)
    ax3.set_xlim(-zoom_area, zoom_area)
    ax3.set_title("Профиль интенсивности")
    st.pyplot(fig_line)